contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "PHAS0100: Research Computing with C++"
includeleftnav: True
short: PHAS0100

defaults:
  - scope: {path: ""}
    values: {layout: default, slidelink: true}

baseurl: /research-computing-with-cpp

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: Our services
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: Research IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: Training

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]

idio:
  fence: True

include: [ _static, _sources]
exclude:
  - 02libraries
  - 03cpp
  - 03cpppatterns
  - 04HPC
  - 05OpenMP
  - 06MPI
  - 07PythonBinding
  - 08Summary2019
  - 88cpplibraries
  - 90stl
  - 92TemplateMetaProg 
  - 93MPIExample
  - 94MPIIO
  - 95CodeQuality  
  - 96Cloud
  - 97Accelerators
  - combined.md
  - build
  - "*.tmd"
  - "*.rmd"
  - "*.out"
  - "*.cc"
  - "*.cpp"
  - "*.h"
  - "*.x"
  - "*.rb"
  - Makefile
  - CMakeLists.txt
  - cpp
