contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "COMP0210: Research Computing with C++"
includeleftnav: True
short: COMP0210

defaults:
  - scope: {path: ""}
    values: {layout: default, slidelink: false}

baseurl: /research-computing-with-cpp

remote_theme: UCL-ARC/indigo-jekyll


crumbs:
  - link: https://www.ucl.ac.uk/arc
    text: Advanced Research Computing
  - link: https://www.ucl.ac.uk/advanced-research-computing/about-our-training
    text: Training

markdown: kramdown

kramdown:
  hard_wrap: false

idio:
  fence: True

include: [ _static, _sources]
exclude:
  - 05libraries/sec05CMake*.md
  - 03cpppatterns
  - 04HPC
  - 05OpenMP
  - 06MPI
  - 07PythonBinding
  - 08Summary2019
  - 88cpplibraries
  - 90stl
  - 92TemplateMetaProg 
  - 93MPIExample
  - 94MPIIO
  - 95CodeQuality  
  - 96Cloud
  - 97Accelerators
  - combined.md
  - build
  - "*.tmd"
  - "*.rmd"
  - "*.out"
  - "*.cc"
  - "*.cpp"
  - "*.h"
  - "*.x"
  - "*.rb"
  - Makefile
  - CMakeLists.txt
  - cpp
  - vendor
